function getCharacters(sorting) {
    var collection = [
        { id: 1, character: "Alice", job: "" },
        { id: 2, character: "Snow White", job: "" },
        { id: 3, character: "Red Riding Hood", job: "" },
        { id: 4, character: "Cinderella", job: "" },
        { id: 5, character: "Pinocchio", job: "" },
        { id: 6, character: "Briar Rose", job: "" },
        { id: 7, character: "Gretel", job: "" },
        { id: 8, character: "Kaguya", job: "" },
        { id: 9, character: "Alice", job: "" },
        { id: 10, character: "Snow White", job: "" },
        { id: 11, character: "Red Riding Hood", job: "" },
        { id: 12, character: "Cinderella", job: "" },
        { id: 13, character: "Pinocchio", job: "" },
        { id: 14, character: "Briar Rose", job: "" },
        { id: 15, character: "Gretel", job: "" },
        { id: 16, character: "Kaguya", job: "" },
        { id: 17, character: "Snow White", job: "" },
        { id: 18, character: "Briar Rose", job: "" },
        { id: 19, character: "Gretel", job: "" },
        { id: 20, character: "Pinocchio", job: "" },
        { id: 21, character: "Cinderella", job: "" },
        { id: 22, character: "Alice", job: "" },
        { id: 23, character: "Red Riding Hood", job: "" },
        { id: 24, character: "Kaguya", job: "" },
        { id: 25, character: "Little Mermaid", job: "" },
        { id: 26, character: "Little Mermaid", job: "" },
        { id: 27, character: "Little Mermaid", job: "" },
        { id: 28, character: "Kaguya", job: "" },
        { id: 29, character: "Alice", job: "" },
        { id: 30, character: "Pinocchio", job: "" },
        { id: 31, character: "Red Riding Hood", job: "" },
        { id: 32, character: "Alice", job: "" },
        { id: 33, character: "Red Riding Hood", job: "" },
        { id: 34, character: "Briar Rose", job: "" },
        { id: 35, character: "Cinderella", job: "" },
        { id: 36, character: "ZZZ Nier Automata", job: "" },
        { id: 37, character: "ZZZ Nier Automata", job: "" },
        { id: 38, character: "ZZZ Nier Automata", job: "" },
        { id: 39, character: "ZZZ Nier Automata", job: "" },
        { id: 40, character: "ZZZ Nier Automata", job: "" },
        { id: 42, character: "Gretel", job: "" },
        { id: 43, character: "Dorothy", job: "" },
        { id: 44, character: "Alice", job: "" },
        { id: 45, character: "Dorothy", job: "" },
        { id: 46, character: "Snow White", job: "" },
        { id: 47, character: "Briar Rose", job: "" },
        { id: 48, character: "Alice", job: "" },
        { id: 49, character: "Gretel", job: "" },
        { id: 50, character: "Little Mermaid", job: "" },
        { id: 51, character: "Pinocchio", job: "" },
        { id: 52, character: "Red Riding Hood", job: "" },
        { id: 53, character: "Cinderella", job: "" },
        { id: 55, character: "Gretel", job: "" },
        { id: 56, character: "Alice", job: "" },
        { id: 57, character: "Nutcracker", job: "" },
        { id: 58, character: "Kaguya", job: "" },
        { id: 59, character: "Snow White", job: "" },
        { id: 60, character: "Red Riding Hood", job: "" },
        { id: 61, character: "Snow White", job: "" },
        { id: 62, character: "Pinocchio", job: "" },
        { id: 63, character: "Little Mermaid", job: "" },
        { id: 64, character: "Snow White", job: "" },
        { id: 65, character: "Alice", job: "" },
        { id: 66, character: "Red Riding Hood", job: "" },
        { id: 67, character: "Cinderella", job: "" },
        { id: 68, character: "Dorothy", job: "" },
        { id: 69, character: "Cinderella", job: "" },
        { id: 70, character: "ZZZ Drakengard", job: "" },
        { id: 71, character: "ZZZ Drakengard", job: "" },
        { id: 72, character: "ZZZ Drakengard", job: "" },
        { id: 73, character: "ZZZ Drakengard", job: "" },
        { id: 74, character: "ZZZ Drakengard", job: "" },
        { id: 75, character: "Three Little Piggies", job: "" },
        { id: 76, character: "Snow White", job: "" },
        { id: 77, character: "Alice", job: "" },
        { id: 78, character: "Gretel", job: "" },
        { id: 79, character: "Kaguya", job: "" },
        { id: 80, character: "Little Mermaid", job: "" },
        { id: 81, character: "Dorothy", job: "" },
        { id: 82, character: "Snow White", job: "" },
        { id: 83, character: "Pinocchio", job: "" },
        { id: 84, character: "Dorothy", job: "" },
        { id: 85, character: "Briar Rose", job: "" },
        { id: 86, character: "Little Mermaid", job: "" },
        { id: 88, character: "Briar Rose", job: "" },
        { id: 89, character: "Cinderella", job: "" },
        { id: 90, character: "Cinderella", job: "" },
        { id: 91, character: "Briar Rose", job: "" },
        { id: 92, character: "Little Mermaid", job: "" },
        { id: 93, character: "Gretel", job: "" },
        { id: 94, character: "Kaguya", job: "" },
        { id: 95, character: "Red Riding Hood", job: "" },
        { id: 96, character: "Three Little Piggies", job: "" },
        { id: 97, character: "Snow White", job: "" },
        { id: 98, character: "Gretel", job: "" },
        { id: 99, character: "Alice", job: "" },
        { id: 100, character: "Alice", job: "" },
        { id: 101, character: "Dorothy", job: "" },
        { id: 102, character: "Little Mermaid", job: "" },
        { id: 103, character: "Red Riding Hood", job: "" },
        { id: 104, character: "Briar Rose", job: "" },
        { id: 105, character: "Little Mermaid", job: "" },
        { id: 106, character: "Pinocchio", job: "" },
        { id: 107, character: "Alice", job: "" },
        { id: 108, character: "Gretel", job: "" },
        { id: 109, character: "Alice", job: "" },
        { id: 110, character: "Dorothy", job: "" },
        { id: 111, character: "Snow White", job: "" },
        { id: 112, character: "Nutcracker", job: "" },
        { id: 113, character: "Pinocchio", job: "" },
        { id: 114, character: "Little Mermaid", job: "" },
        { id: 115, character: "Alice", job: "" },
        { id: 116, character: "Briar Rose", job: "" },
        { id: 118, character: "Cinderella", job: "" },
        { id: 119, character: "Red Riding Hood", job: "" },
        { id: 120, character: "Aladdin", job: "" },
        { id: 121, character: "Three Little Piggies", job: "" },
        { id: 122, character: "Kaguya", job: "" },
        { id: 123, character: "Dorothy", job: "" },
        { id: 124, character: "Gretel", job: "" },
        { id: 125, character: "Dorothy", job: "" },
        { id: 126, character: "Kaguya", job: "" },
        { id: 127, character: "Pinocchio", job: "" },
        { id: 128, character: "Snow White", job: "" },
        { id: 129, character: "Little Mermaid", job: "" },
        { id: 130, character: "Cinderella", job: "" },
        { id: 131, character: "Kaguya", job: "" },
        { id: 132, character: "Snow White", job: "" },
        { id: 133, character: "Gretel", job: "" },
        { id: 134, character: "Red Riding Hood", job: "" },
        { id: 135, character: "Alice", job: "" },
        { id: 136, character: "Kaguya", job: "" },
        { id: 137, character: "Three Little Piggies", job: "" },
        { id: 138, character: "Gretel", job: "" },
        { id: 139, character: "Cinderella", job: "" },
        { id: 140, character: "Kaguya", job: "" },
        { id: 141, character: "Dorothy", job: "" },
        { id: 142, character: "Nutcracker", job: "" },
        { id: 143, character: "Snow White", job: "" },
        { id: 144, character: "Red Riding Hood", job: "" },
        { id: 145, character: "Pinocchio", job: "" },
        { id: 146, character: "Kaguya", job: "" },
        { id: 147, character: "Aladdin", job: "" },
        { id: 148, character: "Snow White", job: "" },
        { id: 149, character: "Pinocchio", job: "" },
        { id: 150, character: "Briar Rose", job: "" },
        { id: 151, character: "Gretel", job: "" },
        { id: 153, character: "Rapunzel", job: "" },
        { id: 154, character: "Alice", job: "" },
        { id: 155, character: "Nutcracker", job: "" },
        { id: 156, character: "Cinderella", job: "" },
        { id: 157, character: "ZZZ Nier Replicant", job: "" },
        { id: 158, character: "ZZZ Nier Replicant", job: "" },
        { id: 159, character: "ZZZ Nier Replicant", job: "" },
        { id: 160, character: "ZZZ Nier Replicant", job: "" },
        { id: 161, character: "ZZZ Nier Replicant", job: "" },
        { id: 162, character: "ZZZ Nier Replicant", job: "" },
        { id: 163, character: "Dorothy", job: "" },
        { id: 164, character: "Snow White", job: "" },
        { id: 165, character: "Briar Rose", job: "" },
        { id: 166, character: "Pinocchio", job: "" },
        { id: 167, character: "Pinocchio", job: "" },
        { id: 170, character: "Aladdin", job: "" },
        { id: 171, character: "Little Mermaid", job: "" },
        { id: 172, character: "Kaguya", job: "" },
        { id: 173, character: "Alice", job: "" },
        { id: 174, character: "Dorothy", job: "" },
        { id: 175, character: "Briar Rose", job: "" },
        { id: 177, character: "Alice", job: "" },
        { id: 178, character: "Gretel", job: "" },
        { id: 179, character: "Snow White", job: "" },
        { id: 180, character: "Briar Rose", job: "" },
        { id: 181, character: "Alice", job: "" },
        { id: 182, character: "Little Mermaid", job: "" },
        { id: 183, character: "Kaguya", job: "" },
        { id: 184, character: "Aladdin", job: "" },
        { id: 185, character: "Cinderella", job: "" },
        { id: 187, character: "Dorothy", job: "" },
        { id: 188, character: "Briar Rose", job: "" },
        { id: 189, character: "Alice", job: "" },
        { id: 190, character: "Little Mermaid", job: "" },
        { id: 191, character: "Briar Rose", job: "" },
        { id: 192, character: "Cinderella", job: "" },
        { id: 193, character: "Alice", job: "" },
        { id: 194, character: "Snow White", job: "" },
        { id: 195, character: "Snow White", job: "" },
        { id: 196, character: "Alice", job: "" },
        { id: 197, character: "Cinderella", job: "" },
        { id: 198, character: "Red Riding Hood", job: "" },
        { id: 199, character: "Nutcracker", job: "" },
        { id: 200, character: "ZZZ Drakengard", job: "" },
        { id: 201, character: "ZZZ Drakengard", job: "" },
        { id: 202, character: "ZZZ Drakengard", job: "" },
        { id: 203, character: "ZZZ Drakengard", job: "" },
        { id: 204, character: "Three Little Piggies", job: "" },
        { id: 205, character: "Pinocchio", job: "" },
        { id: 206, character: "Snow White", job: "" },
        { id: 207, character: "ZZZ Code Geass", job: "" },
        { id: 208, character: "ZZZ Code Geass", job: "" },
        { id: 209, character: "ZZZ Code Geass", job: "" },
        { id: 210, character: "ZZZ Code Geass", job: "" },
        { id: 211, character: "ZZZ Code Geass", job: "" },
        { id: 212, character: "ZZZ Code Geass", job: "" },
        { id: 213, character: "Dorothy", job: "" },
        { id: 214, character: "Red Riding Hood", job: "" },
        { id: 215, character: "Cinderella", job: "" },
        { id: 216, character: "Rapunzel", job: "" },
        { id: 217, character: "Briar Rose", job: "" },
        { id: 218, character: "Gretel", job: "" },
        { id: 219, character: "Little Mermaid", job: "" },
        { id: 220, character: "Aladdin", job: "" },
        { id: 221, character: "Kaguya", job: "" },
        { id: 222, character: "ZZZ Brave Exvius", job: "" },
        { id: 223, character: "ZZZ Brave Exvius", job: "" },
        { id: 224, character: "Little Mermaid", job: "" },
        { id: 225, character: "Three Little Piggies", job: "" },
        { id: 227, character: "Snow White", job: "" },
        { id: 228, character: "Red Riding Hood", job: "" },
        { id: 229, character: "Pinocchio", job: "" },
        { id: 230, character: "Hamelin", job: "" },
        { id: 231, character: "Dorothy", job: "" },
        { id: 232, character: "Dorothy", job: "" },
        { id: 233, character: "Aladdin", job: "" },
        { id: 234, character: "Pinocchio", job: "" },
        { id: 235, character: "Gretel", job: "" },
        { id: 236, character: "Nutcracker", job: "" },
        { id: 237, character: "Alice", job: "" },
        { id: 238, character: "Little Mermaid", job: "" },
        { id: 239, character: "Dorothy", job: "" },
        { id: 240, character: "Gretel", job: "" },
        { id: 241, character: "Red Riding Hood", job: "" },
        { id: 242, character: "ZZZ ReZero", job: "" },
        { id: 243, character: "ZZZ ReZero", job: "" },
        { id: 244, character: "ZZZ ReZero", job: "" },
        { id: 245, character: "ZZZ ReZero", job: "" },
        { id: 246, character: "ZZZ ReZero", job: "" },
        { id: 247, character: "Rapunzel", job: "" },
        { id: 249, character: "ZZZ ReZero", job: "" },
        { id: 250, character: "Pinocchio", job: "" },
        { id: 251, character: "Aladdin", job: "" },
        { id: 252, character: "Little Mermaid", job: "" },
        { id: 254, character: "Alice", job: "" },
        { id: 255, character: "Briar Rose", job: "" },
        { id: 256, character: "Kaguya", job: "" },
        { id: 257, character: "Snow White", job: "" },
        { id: 258, character: "Rapunzel", job: "" },
        { id: 259, character: "Briar Rose", job: "" },
        { id: 260, character: "Aladdin", job: "" },
        { id: 261, character: "Three Little Piggies", job: "" },
        { id: 264, character: "Briar Rose", job: "" },
        { id: 265, character: "Pinocchio", job: "" },
        { id: 266, character: "Cinderella", job: "" },
        { id: 267, character: "Dorothy", job: "" },
        { id: 268, character: "Gretel", job: "" },
        { id: 269, character: "Three Little Piggies", job: "" },
        { id: 270, character: "Kaguya", job: "" },
        { id: 271, character: "Three Little Piggies", job: "" },
        { id: 272, character: "Gretel", job: "" },
        { id: 273, character: "Hamelin", job: "" },
        { id: 274, character: "Alice", job: "" },
        { id: 275, character: "Kaguya", job: "" },
        { id: 277, character: "Red Riding Hood", job: "" },
        { id: 278, character: "Gretel", job: "" },
        { id: 279, character: "Cinderella", job: "" },
        { id: 280, character: "Three Little Piggies", job: "" },
        { id: 281, character: "Red Riding Hood", job: "" },
        { id: 282, character: "Snow White", job: "" },
        { id: 283, character: "Rapunzel", job: "" },
        { id: 284, character: "Aladdin", job: "" },
        { id: 285, character: "Little Mermaid", job: "" },
        { id: 286, character: "Kaguya", job: "" },
        { id: 287, character: "Pinocchio", job: "" },
        { id: 288, character: "Rapunzel", job: "" },
        { id: 289, character: "Alice", job: "" },
        { id: 290, character: "Gretel", job: "" },
        { id: 291, character: "Cinderella", job: "" },
        { id: 292, character: "Hamelin", job: "" },
        { id: 293, character: "Three Little Piggies", job: "" },
        { id: 294, character: "Kaguya", job: "" },
        { id: 295, character: "Snow White", job: "" },
        { id: 296, character: "Briar Rose", job: "" },
        { id: 297, character: "Little Mermaid", job: "" },
        { id: 298, character: "Little Mermaid", job: "" },
        { id: 299, character: "Red Riding Hood", job: "" },
        { id: 300, character: "Kaguya", job: "" },
        { id: 301, character: "Alice", job: "" },
        { id: 302, character: "Rapunzel", job: "" },
        { id: 303, character: "Briar Rose", job: "" },
        { id: 304, character: "ZZZ GEMS COMPANY", job: "" },
        { id: 305, character: "Snow White", job: "" },
        { id: 308, character: "Alice", job: "" },
        { id: 309, character: "Little Mermaid", job: "" },
        { id: 310, character: "Dorothy", job: "" },
        { id: 311, character: "Aladdin", job: "" },
        { id: 312, character: "Cinderella", job: "" },
        { id: 313, character: "Briar Rose", job: "" },
        { id: 314, character: "Pinocchio", job: "" },
        { id: 315, character: "Red Riding Hood", job: "" },
        { id: 316, character: "Little Mermaid", job: "" },
        { id: 317, character: "ZZZ GEMS COMPANY", job: "" },
        { id: 322, character: "Rapunzel", job: "" },
        { id: 323, character: "Snow White", job: "" },
        { id: 324, character: "Gretel", job: "" },
        { id: 325, character: "Kaguya", job: "" },
        { id: 326, character: "Nutcracker", job: "" },
        { id: 327, character: "Three Little Piggies", job: "" },
        { id: 328, character: "Hamelin", job: "" },
        { id: 329, character: "Snow White", job: "" },
        { id: 330, character: "Hamelin", job: "" },
        { id: 331, character: "ZZZ Nier Replicant", job: "" },
        { id: 332, character: "ZZZ Nier Replicant", job: "" },
        { id: 333, character: "Alice", job: "" },
        { id: 334, character: "Little Mermaid", job: "" },
        { id: 335, character: "Snow White", job: "" },
        { id: 336, character: "Briar Rose", job: "" },
    ]

    if (sorting == 1) {
        collection.sort(function (x, y) {
            return x.character.localeCompare(y.character);
        });
    }
    else if (sorting == 2) {
        collection.sort(function (x, y) {
            return x.job.localeCompare(y.job);
        });
    }

    var newCollection = [];
    for (var i = 0; i < collection.length; ++i) {
        newCollection.push(collection[i]["id"]);
    }

    return newCollection;
}
